### ISSUE TITLE
module 'PIL' has no attribute 'Image'

### ISSUE THREAD

**Issue by TIGER96** [alcortazzo/vktgbot#17]
How to solve this problem?

[WARNING] Something [AttributeError] went wrong in sendPosts() [post id:1232561] [1 try of 5]: module 'PIL' has no attribute 'Image'

**Comment by JargeZ** [comment]
hi
How often do you get this error?

Can you change a few lines of code to understand exactly where the error occurs?
In file `bot.py` line 371 function `sendPosts()` change
```
            except Exception as ex:
```
to
```
            except Exception as ex:
                import traceback
                traceback.print_tb(ex.__traceback__)
```
And write when you catch this problem again
