### ISSUE TITLE
[ERROR] Exception in type IndexError in checkNewPost(): list index out of range

### ISSUE THREAD

**Issue by m1ronow** [alcortazzo/vktgbot#19]
![image](https://user-images.githubusercontent.com/45268080/106479093-f90cea80-64ba-11eb-967b-cd36b85b19b1.png)

никак не получилось пофиксить, конфиг заполнен по инструкции

**Comment by alcortazzo** [comment]
У целевого ВК паблика стоит стандартный, неизмененный адрес (прим. `vk.com/public1234556789`)? Если есть возможность - поменяй его на свой и используй его.

В противном случае - попробуй в `vkDomain` вписать id паблика (цифры, начинающиеся с минуса). Его можно достать из ссылки на любой пост паблика. Например, `https://vk.com/wall-22822305_1148195`, где `-22822305` - это id. Подобный способ я не тестировал, но, теоретически - может сработать.

**Comment by m1ronow** [comment]
> У целевого ВК паблика стоит стандартный, неизмененный адрес (прим. `vk.com/public1234556789`)? Если есть возможность - поменяй его на свой и используй его.
> 
> В противном случае - попробуй в `vkDomain` вписать id паблика (цифры, начинающиеся с минуса). Его можно достать из ссылки на любой пост паблика. Например, `https://vk.com/wall-22822305_1148195`, где `-22822305` - это id. Подобный способ я не тестировал, но, теоретически - может сработать.

Проблема была в токене, вк почему то на фейковом аккаунте выдавал нерабочие, видимо сам аккаунт в какой то блокировке

**Comment by alcortazzo** [comment]
> > У целевого ВК паблика стоит стандартный, неизмененный адрес (прим. `vk.com/public1234556789`)? Если есть возможность - поменяй его на свой и используй его.
> > В противном случае - попробуй в `vkDomain` вписать id паблика (цифры, начинающиеся с минуса). Его можно достать из ссылки на любой пост паблика. Например, `https://vk.com/wall-22822305_1148195`, где `-22822305` - это id. Подобный способ я не тестировал, но, теоретически - может сработать.
> 
> Проблема была в токене, вк почему то на фейковом аккаунте выдавал нерабочие, видимо сам аккаунт в какой то блокировке

**Насколько мне известно**, ВК может деактивировать токены, если превышены лимиты их использования или по каким-то другим причинам. Можете попробовать пересоздать токен на фейковом аккаунте - вполне возможно, заработает.

Также, возможно, паблик является приватным, а фейковая страница в нем не состоит - потому и токен не давал результатов.

**Comment by m1ronow** [comment]
> > > У целевого ВК паблика стоит стандартный, неизмененный адрес (прим. `vk.com/public1234556789`)? Если есть возможность - поменяй его на свой и используй его.
> > > В противном случае - попробуй в `vkDomain` вписать id паблика (цифры, начинающиеся с минуса). Его можно достать из ссылки на любой пост паблика. Например, `https://vk.com/wall-22822305_1148195`, где `-22822305` - это id. Подобный способ я не тестировал, но, теоретически - может сработать.
> > 
> > 
> > Проблема была в токене, вк почему то на фейковом аккаунте выдавал нерабочие, видимо сам аккаунт в какой то блокировке
> 
> **Насколько мне известно**, ВК может деактивировать токены, если превышены лимиты их использования или по каким-то другим причинам. Можете попробовать пересоздать токен на фейковом аккаунте - вполне возможно, заработает.
> 
> Также, возможно, паблик является приватным, а фейковая страница в нем не состоит - потому и токен не давал результатов.

Токен пересоздавал 3 раза, паблик открытый, скорее всего вк по какой то причине блокировал токены на том аккаунте
