### ISSUE TITLE
style mono-wide text code

### ISSUE THREAD

**Issue by MilaFabio** [alcortazzo/vktgbot#23]
The bot makes a repost of the text in which there is text in apostrophes, which in telegram is a mono-wide text (or a font for the code that can be copied by clicking). 

But this text is published in the channel without taking this into account, so just TEXT, not `TEXT`

how to make the text in apostrophes inserted as a monofilament. If you click edit and just save, then this style is immediately applied?

**Comment by alcortazzo** [comment]
Bot uses HTML parse mode. 
Code in apostrophes  - Markdown syntax.
