### ISSUE TITLE
Отсутсвие возможности делать PR

### ISSUE THREAD

**Issue by granescb** [alcortazzo/vktgbot#35]
Не могу вылить ветку чтобы сделать PR)
Сделал небольшую правку в функции get_data()
Перед return data.json()["response"]["items"]
вставить:

json_data = data.json()
if json_data.get('error'):
    add_log(
        "w",
        f""" get_data() failed, VK response: error_code: {json_data.get('error_code')},
        error_msg: {json_data.get('error_msg')}"""
    )
    raise Exception("Can't get data from VK")

**Comment by alcortazzo** [comment]
Я набрался опыта и уже работаю над тем, что полностью, с нуля, переписываю проект.
Там обработка подобных вещей будет учтена.  Спасибо.
