### ISSUE TITLE
Перестали отправляться сообщения

### ISSUE THREAD

**Issue by TIGER96** [alcortazzo/vktgbot#38]
Как в старой версии, так и в новой, уже более недели нет сообщений от бота.

Везде сообщение одинаковое Got a few posts with IDs: 49 - 51.
А после уходит в сон.

 | INFO     | api_requests:get_data_from_vk:10 - Trying to get posts from VK.
 | INFO     | start_script:start_script:34 - Got a few posts with IDs: 49 - 51.
 | INFO     | __main__:<module>:35 - Script went to sleep for 120 seconds.

**Comment by alcortazzo** [comment]
Проблема всё еще актуальна? Потому что у меня воспроизвести её не получилось.
Если да, предоставьте более подробную информацию о ней: файл логов и адрес паблика, который не удается спарсить.
