### ISSUE TITLE
Excepion in type KeyError in checkNewPost(): 'marked_as_ads'

### ISSUE THREAD

**Issue by justice47** [alcortazzo/vktgbot#4]
Hi!
I've got the error - "Excepion in type KeyError in checkNewPost(): 'marked_as_ads'" just after scanning start:
```
 | [VK] Started scanning for new posts
 | [Info] Last id of vk post is 0
```

**Comment by alcortazzo** [comment]
Напиши версию Python и целевой вк паблик откуда пытаешься парсить посты
