### ISSUE TITLE
Не корректно публикуются видео на версии 3.0

### ISSUE THREAD

**Issue by vlab97** [alcortazzo/vktgbot#42]
На версии 3.0 публикуется изображение без ссылки на видео

**Comment by vlab97** [comment]
На десктопных версиях Telegram можно перейти к видео. На мобильной версии (IOS) нет возможности для перехода к видео.

**Comment by alcortazzo** [comment]
> На десктопных версиях Telegram можно перейти к видео. На мобильной версии (IOS) нет возможности для перехода к видео.

Да, спасибо. Сам только что обратил внимание на то, что с мобильной версии превью видео не кликабельно.
