### ISSUE TITLE
Кастомизация отправляемого сообщения

### ISSUE THREAD

**Issue by els777** [alcortazzo/vktgbot#43]
Возник вопрос в кастомизации исходящего сообщения. Т.е. есть паблик, в котором находятся только изображения, но в тг, хотелось бы сделать возможность дописывания своего текста. Например, источник.

**Comment by alcortazzo** [comment]
Может когда-нибудь сделаю.

**Comment by els777** [comment]
В настоящий момент под себя изменил и заменил text в постинге изображений. Но моих знаний Python недостаточно, чтобы сделать что-то большее. Зато теперь не проверяется весь текст из поста в ВК.
