### ISSUE TITLE
Можно сделать переключатель с файла на картинку?

### ISSUE THREAD

**Issue by BVADI** [alcortazzo/vktgbot#50]
Хотелось бы видеть вместо файла, картинку с текстом.

Пост: 
![image](https://user-images.githubusercontent.com/24761089/188273911-4e7af062-3d34-46f7-8147-4c05290d9dbf.png)

Репост в ТГ
![image](https://user-images.githubusercontent.com/24761089/188273925-8868a5ba-96da-4004-bff0-2251fa3c3323.png)

**Comment by alcortazzo** [comment]
Задача бота — дублировать посты из ВК в ТГ в том виде, в котором они изначально представлены (с учётом некоторых ограничений и специфики Телеграма).
Дополнительно реализовывать переключатели под хотелки всех, кому что-то нужно изменить в скрипте, у меня нет ни времени, ни желания. Вы можете сделать форк и самостоятельно изменить код под ваши нужды.
