### ISSUE TITLE
Текс больше 1024 символов, картинка в виде превью :(

### ISSUE THREAD

**Issue by BVADI** [alcortazzo/vktgbot#51]
Как это переключить на отправку картинки + текст?

Хотелось бы и большое кол-во фоток + текст в такой же последовательности ,сначала фото потом текст.

**Comment by alcortazzo** [comment]
Задача бота — дублировать посты из ВК в ТГ в том виде, в котором они изначально представлены (с учётом некоторых ограничений и специфики Телеграма).
Дополнительно реализовывать переключатели под хотелки всех, кому что-то нужно изменить в скрипте, у меня нет ни времени, ни желания. Вы можете сделать форк и самостоятельно изменить код под ваши нужды.
