### ISSUE TITLE
Фичи и переключатели

### ISSUE THREAD

**Issue by BVADI** [alcortazzo/vktgbot#52]
Есть обработчик json на php для другого проекта, с кучей переключателей.. может он поможет и ускорит дополнение фич.
Например, очень бы хотелось, если репост завершается с ошибкой (токен просрочился, файл/видео не пролезает и тд) выплевывалась бы ошибка не в лог, а напрямую боту, по сути бот бы слал в личку.

[mmb.txt](https://github.com/alcortazzo/vktgbot/files/9482774/mmb.txt)

Например выключение превью:
.env
+VAR_DISABLE_WEB_PAGE_PREVIEW = True

config.py
+DISABLE_WEB_PAGE_PREVIEW: bool = os.getenv("VAR_DISABLE_WEB_PAGE_PREVIEW", "").lower() in ("true")

send_posts.py
+import config

    if len(text) < 4096:
        await bot.send_message(tg_channel, text, parse_mode=types.ParseMode.HTML, disable_web_page_preview=config.DISABLE_WEB_PAGE_PREVIEW)

        for part in prepared_text_parts:
            await bot.send_message(tg_channel, part, parse_mode=types.ParseMode.HTML, disable_web_page_preview=config.DISABLE_WEB_PAGE_PREVIEW)

            await bot.send_message(
                tg_channel, prepared_text, parse_mode=types.ParseMode.HTML, disable_web_page_preview=config.DISABLE_WEB_PAGE_PREVIEW

**Comment by alcortazzo** [comment]
Функционал отправки логов в канал Телеграма был реализован в старой (v2.6) версии бота, до того как код был полностью переписан. Можете воспользоваться этой версией, склонировав её по инструкции в README.
Касаемо остального ответил в предыдущих issues.
