### ISSUE TITLE
При перепосте с вк в тг теряется ссылка на автора объявления

### ISSUE THREAD

**Issue by spaceVpn** [alcortazzo/vktgbot#56]
Здравствуйте.
Вы бы могли посмотреть, что не так...
При перепосте с вк в тг теряется ссылка на автора объявления.
Группа для примера:
https://vk.com/znakomstva_obshchenie_druzhba - вставляет просто фото и текст без ссылки на вк
Это происходит не только в этой группе но и в других такой же тематики...

![34](https://user-images.githubusercontent.com/102386160/213485031-6134fd51-c802-460a-a29c-9afa8c76944c.png)

**Comment by alcortazzo** [comment]
Такой функционал не реализован. Ссьілки на авторов записей не прикрепляются.

**Comment by VernadskyDanya** [comment]
Да, жалко. Буду иметь в виду. Спасибо!
