### ISSUE TITLE
Кроме получения постов больше ничего не происходит

### ISSUE THREAD

**Issue by Sidiusz** [alcortazzo/vktgbot#59]
Кроме получения постов больше ничего не происходит, ТГ канал публичный, бот администратор

```
docker-app-1  | 2023-04-16 05:22:07.044 | INFO     | start_script:start_script:20 - Last known ID: 1685486
docker-app-1  | 2023-04-16 05:22:07.045 | INFO     | api_requests:get_data_from_vk:11 - Trying to get posts from VK.
docker-app-1  | 2023-04-16 05:22:07.287 | INFO     | start_script:start_script:34 - Got a few posts with IDs: 1685454 - 1685486.
docker-app-1  | 2023-04-16 05:22:07.288 | INFO     | __main__:<module>:41 - Script went to sleep for 120 seconds.
```

 - Windows 11
 - Docker 4.18.0

**Comment by alcortazzo** [comment]
Судя по тем логам, что вьі указали, бот ничего не делает, поскольку он последний пост уже обработал.
А так, трудно что-то сказать без конкретньіх данньіх или примеров.

**Comment by Sidiusz** [comment]
>бот ничего не делает, поскольку он последний пост уже обработал
И что же он сделал? Он получил инфу, написал "я получил" и.. всё

**Comment by alcortazzo** [comment]
Без понимания того как настроен бот, какие постьі он получает и куда пьітается отправлять - я даже предположить о причинах такого поведения не могу.

Скиньте содержимое конфига (только уберите токеньі).

**Comment by specoff** [comment]
> > бот ничего не делает, поскольку он последний пост уже обработал
> 
> И что же он сделал? Он получил инфу, написал "я получил" и.. всё

Смотрите настройки бота ТГ. 
Разрешение у бота есть? Разные вкладки в ботфатер для группы и канала.
В настройках бота (у BotFather) во вкладке «Allow groups» у бота указана группа или канал куда необходимо публиковать?
Я бы с этого начал поиск. У меня работает этот скрипт уже давно.
