### ISSUE TITLE
Репост из нескольких пабликов в ВК

### ISSUE THREAD

**Issue by finn1199** [alcortazzo/vktgbot#65]
Не совсем понятно, из нескольких пабликов в ВК данный скрипт умеет репостить?
Из одного понятно, всё работает:
VAR_VK_DOMAIN = durov

А если помимо durov нужно из др. пабликов ещё организовать репосты?
Спасибо!

**Comment by alcortazzo** [comment]
Версия бота в ветке v4-dev - умеет

**Comment by finn1199** [comment]
> Версия бота в ветке v4-dev - умеет

Спасибо!
Не внимательно Git смотрел.

Не завёлся v4 бот.
Высыпал ошибок...
Не находит модули.
Отредактировал код по import и from почти во всех модулях/скриптах в папке vktgbot и всё заработало.
Парсит/репостит прекрасно одновременно со многих ВК-пабликов в мой TG-канал.

**Comment by alcortazzo** [comment]
> > Версия бота в ветке v4-dev - умеет
> 
> 
> 
> Спасибо!
> 
> Не внимательно Git смотрел.
> 
> 
> 
> Не завёлся v4 бот.
> 
> Высыпал ошибок...
> 
> Не находит модули.
> 
> Отредактировал код по import и from почти во всех модулях/скриптах в папке vktgbot и всё заработало.
> 
> Парсит/репостит прекрасно одновременно со многих ВК-пабликов в мой TG-канал.

Его нужно запускать так `python -m vktgbot`

**Comment by finn1199** [comment]
> > > Версия бота в ветке v4-dev - умеет
> > 
> > 
> > Спасибо!
> > Не внимательно Git смотрел.
> > Не завёлся v4 бот.
> > Высыпал ошибок...
> > Не находит модули.
> > Отредактировал код по import и from почти во всех модулях/скриптах в папке vktgbot и всё заработало.
> > Парсит/репостит прекрасно одновременно со многих ВК-пабликов в мой TG-канал.
> 
> Его нужно запускать так `python -m vktgbot`

Спасибо!
Приеду домой попробую.

**Comment by finn1199** [comment]
Всё работает.
Спасибо!!!
