### ISSUE TITLE
How to do don't start parsing posts again from last-nown posts ID to TG after reboot pc/server/bot, but start do that from actual last-published post by Bot befor crash or rebot pc/server/bot?

### ISSUE THREAD

**Issue by finn1199** [alcortazzo/vktgbot#66]
Доброго дня!
v4-dev
Я правильно понимаю, судя по config.yaml, что настройки не позволяют настройку (я во всяком случае не нашёл таковых) в случае падения бота или ребута рс/сервера/бота не запускать снова репост с последнего указанного id поста в ВК, т.к. у меня например вчера VPS-сервер с установленным ботом упал, пришлось ребутнуть и бот снова вывалил за пред. дни все те же самые посты, что репостил до ребута + новые, появившиеся во время ребута, а не с этих появившихся?

И вот обнаружил по логу ещё, что после ребута бот стал бесконечно реконектиться и вываливать одни и те же посты в канал по тем же критериям, что описаны выше заваливая канал этими постами бесконечно...
Пришлось остановить пока бота до выяснения причин.

Спасибо!
С уважением!

Что получилось, debug.log во вложении
[debug.log](https://github.com/alcortazzo/vktgbot/files/13237442/debug.log)

**Comment by thefoxcc** [comment]
Попробуйте использовать версию 3.10 а не 3.11
так же библиотеку aiogram==2.13 у меня все хорошо работает

**Comment by finn1199** [comment]
> aiogram==2.13 у меня все хорошо работает

С этой версией не работает, а с последней работает.
Я немного пошаманил с PATH
Создал запуск через Systemd, наблюдаю...

**Comment by thefoxcc** [comment]
Ок

**Comment by finn1199** [comment]
В общем, всё работает пока хорошо.

Сначала я пробовал запуск бота через Supervisor и прописывал в его конфиге-юните команду на старт:
`cd /home/user/vktgbot && python -m vktgbot`
Работало, но была такая проблема с реконектом и вываливанием кучи уже опубликованных ранее постов.

Сейчас так работает:
- добавил каталог vktgbot в PATH
`PATH="$PATH:/home/user/vktgbot"`
(где вместо user - ваше имя Пользователя в системе)
- создал юнит vktgbot.service в Systemd в /etc/systemd/system/
(полный путь /etc/systemd/system/vktgbot.service)
`[Unit]
Description=Vktgbot
After=multi-user.target

[Service]
Type=idle
User=user
Group=fin
ExecStart=vktgbot

Restart=always
#RestartSec=240`
(вместо user в секции User=**user** ваше имя Пользователя в системе
- запуск и активация бота, как службы Sysemd
`sudo systemctl daemon-reload; sudo systemctl enable --now vktgbot.service`

Всё работает...
