### ISSUE TITLE
Предложение по доработке

### ISSUE THREAD

**Issue by thefoxcc** [alcortazzo/vktgbot#67]
Можно ли сделать исключение к гиперссылкам, имею ввиду что когда в описании поста есть ссылка то его можно бы было не выводит.
реализовать  в конец текста телеграм добавить @tggroup
парсинг с вк на тг определённым групаам вк1= тг1 , вк2 , вк3 =тг2, тг3, тг4 (наверное поняли о чем)

**Comment by thefoxcc** [comment]
так же не работает загрузка видео с вк на тг, а просто ссылку оставляет

**Comment by alcortazzo** [comment]
>Можно ли сделать исключение к гиперссылкам, имею ввиду что когда в описании поста есть ссылка то его можно бы было не выводит.

Думаю можно попробовать вставить в blacklist в конфиге "https://"

>реализовать в конец текста телеграм добавить

У нас реализован функционал репоста. Такие специфичньіе изменения пусть вносятся на стороне пользователей -- кому как нужно.

>парсинг с вк на тг определённым групаам

В ветке v4-dev лежит тестовая версия бота, в которой реализована поддержка асинхронного постинга из нескольких ВК пабликов в несколько ТГ каналов.

>не работает загрузка видео с вк на тг, а просто ссылку оставляет

И не будет работать. Слишком много проблем в реализации, начиная от ограничения в 20 мегабайт на вьігрузку файлов ботами со стороньі Телеграм, заканчивая проблемами с вьігрузки видео со стороньі ВК

**Comment by thefoxcc** [comment]
> Думаю можно попробовать вставить в blacklist в конфиге "https://"
В целом попробовал, не работает ссылки возвращаются 
![image](https://github.com/alcortazzo/vktgbot/assets/94108436/6a0dd8c2-6daf-4655-9d3e-d89909f27eeb)
![image](https://github.com/alcortazzo/vktgbot/assets/94108436/83674b9e-decd-4735-8f05-a1dc9a420405)
